[package]
name = "genre_class_rust_rust_rust"
version = "0.1.0"
authors = ["Marko Lozajic <marko.lozajic@student.uni-tuebingen.de>, Anna Soboleva <anna.soboleva@student.uni-tuebingen.de>"]

[dependencies]
clap = "2"
ndarray = "0.11"
ordered-float = "0.5"
rust-tfidf = "1.0"
scanlex = "0.1"
stopwords = "0.1"
ngrams = "1.0.1"
